name: Ubuntu

on:
  push:
    branches: [ main ]
    tags: 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-test
        run: make test
      - name: pack
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make clean
          make release
          (cd bin/release && zip -r ../../yue-linux-x86_64.zip ./yue)
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./yue-linux-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
